for lrate in 0.01 0.1 0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4; do
	CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --optimizer=momentum --lr=$lrate --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=0 --post-epochs=10 --pruner=mag --prune-epochs=10 --gpu=0 --result-dir=../Data_SynFlow  --expid=cifar10_lottery_vgg11_fixed_bn_lr${lrate} --seed=0 --dataset=cifar10 --model-class=lottery --model=vgg11-bn --compression=0.0 --verbose
done
