for wdrate in 0 0.00001 0.0001 0.001; do
        CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --optimizer=momentum --lr=0.05 --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=60 --post-epochs=0 --pruner=mag --prune-epochs=0 --gpu=0 --result-dir=../Data_SynFlow  --expid=tinyimagenet_lottery_60epochs_vgg11_bn_lr0.05_wd${wdrate}_seed0 --seed=0 --dataset=tiny-imagenet --model-class=tinyimagenet --model=vgg11-bn --compression=0.0
done
