for mom in 0.748 0.800 0.841 0.874 0.9; do
        CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --momentum=$mom --lr=0.1 --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=100 --post-epochs=0 --pruner=mag --prune-epochs=0 --gpu=0 --result-dir=../Results_Noether  --expid=tinyimagenet_lottery_momentum${mom}_100epochs_vgg11_bn_lr0.1_seed0 --seed=0 --dataset=tiny-imagenet --model-class=tinyimagenet --model=vgg11-bn --compression=0.0 --lr-drops 30 60 80
done
