for wdrate in 0 0.000001 0.00000316 0.00001 0.0000316 0.0001 0.000316; do
	CUDA_VISIBLE_DEVICES=1 python3 main.py --experiment=singleshot --optimizer=momentum --lr=0.1 --train-batch-size=128 --weight-decay=$wdrate --pre-epochs=100 --post-epochs=0 --pruner=mag --prune-epochs=0 --gpu=0 --result-dir=../Data_SynFlow  --expid=tinyimagenet_lottery_100epochs_vgg11_fixed_bn_lr0.1_wd${wdrate}_seed0 --seed=0 --dataset=tiny-imagenet --model-class=tinyimagenet --model=vgg11-bn --compression=0.0  --lr-drops 30 60 80 --norm-fix=True
done

